import { ArrowRight, Search } from "lucide-react";
import type { Metadata } from "next";
import Link from "next/link";

import { EmptyState } from "@/components/ui/empty-state";
import { buildSearchIndex, searchContent } from "@/lib/search/search";

export const metadata: Metadata = { title: "Search" };
const labels = { lesson: "Lesson", lab: "Field mission", experiment: "Playground", game: "Quick mission", glossary: "Glossary", practice: "Practice", resource: "Resource", "case-study": "Case study" } as const;
export default async function SearchPage({ searchParams }: { searchParams: Promise<{ q?: string }> }) { const query = (await searchParams).q?.trim() ?? ""; const results = query ? searchContent(buildSearchIndex(), query) : []; return <div className="mx-auto max-w-[900px] px-4 py-14 sm:px-6 lg:px-8"><p className="font-mono text-xs font-semibold uppercase tracking-[0.14em] text-primary">Global search</p><h1 className="mt-3 text-4xl font-semibold tracking-[-0.04em]">Find the field knowledge.</h1><form className="relative mt-8" role="search"><Search aria-hidden="true" className="absolute left-4 top-3.5 size-5 text-muted-foreground" /><input autoFocus className="h-12 w-full rounded-lg border bg-card pl-12 pr-24 text-sm shadow-sm outline-none focus-visible:ring-2 focus-visible:ring-ring" defaultValue={query} name="q" placeholder="Search lessons, games, playgrounds, missions, and templates…" type="search" /><button className="absolute right-2 top-2 h-8 rounded-md bg-primary px-4 text-xs font-semibold text-primary-foreground" type="submit">Search</button></form><div className="mt-8">{query && results.length ? <><p className="mb-3 text-xs text-muted-foreground">{results.length} results for “{query}”</p><div className="overflow-hidden rounded-xl border bg-card">{results.map((result) => <Link className="group grid grid-cols-[1fr_auto] gap-4 border-b p-5 last:border-b-0 hover:bg-muted/25" href={result.href} key={`${result.type}-${result.id}`}><div><span className="font-mono text-[10px] font-semibold uppercase tracking-[0.1em] text-primary">{labels[result.type]}</span><h2 className="mt-2 font-semibold group-hover:text-primary">{result.title}</h2><p className="mt-1 line-clamp-2 text-sm text-muted-foreground">{result.description}</p></div><ArrowRight aria-hidden="true" className="mt-1 size-4 text-muted-foreground group-hover:text-primary" /></Link>)}</div></> : query ? <EmptyState description="Try a customer problem, system concept, skill, simulation, or artifact name." title={`No results for “${query}”`} /> : <EmptyState description="Search across lessons, games, technical playgrounds, field missions, practice scenarios, Northstar releases, glossary terms, and templates." icon={Search} title="Search the entire learning lab" />}</div></div>; }
