import Link from "next/link";
import { z } from "zod";
import { getAllGlossaryEntries, getAllResources } from "@/lib/content";
export const metadata = { title: "Resources" };
const querySchema = z.object({ q: z.string().max(200).catch(""), category: z.enum(["all", "discovery", "architecture", "delivery", "ai", "business"]).catch("all") });
export default async function ResourcesPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const { q, category } = querySchema.parse(await searchParams);
  const terms = q.trim().toLowerCase().split(/\s+/).filter(Boolean);
  const resources = getAllResources().filter((item) => (category === "all" || item.category === category) && terms.every((term) => `${item.title} ${item.description} ${item.body}`.toLowerCase().includes(term)));
  return <div className="mx-auto max-w-[1100px] px-4 py-12 sm:px-6"><p className="font-mono text-xs uppercase tracking-widest text-primary">Field reference</p><h1 className="mt-4 text-4xl font-semibold tracking-tight">Bring the right artifact.</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-muted-foreground">Templates and checklists for customer discovery, architecture, evaluation, production, and handover. Adapt each artifact to your customer’s evidence and constraints.</p>
    <Link className="mt-6 block rounded-lg border p-5 font-semibold text-primary" href="/resources/glossary">FDE glossary → <span className="text-sm font-normal text-muted-foreground">{getAllGlossaryEntries().length} terms linked to learning</span></Link>
    <form className="mt-8 flex flex-wrap items-end gap-3" role="search" aria-label="Find a field template"><label className="min-w-0 flex-1 text-sm">Find a template<input className="mt-2 block h-11 w-full rounded border bg-card px-3" type="search" name="q" defaultValue={q} maxLength={200} /></label><label className="text-sm">Category<select name="category" defaultValue={category} className="mt-2 block h-11 rounded border bg-card px-3">{['all','discovery','architecture','delivery','ai','business'].map((value) => <option key={value} value={value}>{value === 'all' ? 'All categories' : value}</option>)}</select></label><button type="submit" className="h-11 rounded bg-primary px-5 text-sm font-semibold text-primary-foreground">Filter</button></form>
    <section className="mt-10"><h2 className="text-xl font-semibold">Downloadable templates</h2><p className="mt-2 text-sm text-muted-foreground">{resources.length} matching artifacts</p><div className="mt-5 divide-y border-y">{resources.map((resource) => <Link className="block py-5" href={`/resources/templates/${resource.slug}`} key={resource.id}><span className="text-xs uppercase text-primary">{resource.category} · {resource.format}</span><h3 className="mt-2 font-semibold">{resource.title} →</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{resource.description}</p></Link>)}</div>{!resources.length ? <p className="mt-5 text-sm">No matching templates. Try a broader term or <Link className="text-primary underline" href="/resources">clear the filters</Link>.</p> : null}</section>
  </div>;
}
