"use client";

import { ArrowLeft, ArrowRight, Check, Eye, Lightbulb, LoaderCircle, LogIn } from "lucide-react";
import Link from "next/link";
import { useSession } from "next-auth/react";
import { useEffect, useState, useTransition } from "react";

import { updateLabProgress } from "@/app/actions/labs";
import { ProgressBar } from "@/components/learning/progress-bar";
import { Button } from "@/components/ui/button";
import type { Lab } from "@/lib/content/schemas";
import { advanceLabStep, labPercent, type LabState } from "@/lib/labs/progress";

export function LabWorkspace({ lab }: { lab: Lab }) {
  const { data: session, status } = useSession(); const [stepIndex, setStepIndex] = useState(0); const [state, setState] = useState<LabState>({}); const [completed, setCompleted] = useState(false); const [hint, setHint] = useState(false); const [solution, setSolution] = useState(false); const [loaded, setLoaded] = useState(false); const [message, setMessage] = useState(""); const [pending, startTransition] = useTransition();
  useEffect(() => { if (!session?.user) return; let active = true; fetch(`/api/labs/${lab.id}`).then((response) => response.ok ? response.json() as Promise<{ progress: { currentStep: number; state: LabState; completed: boolean } | null }> : { progress: null }).then(({ progress }) => { if (active && progress) { setStepIndex(progress.currentStep); setState(progress.state); setCompleted(progress.completed); } if (active) setLoaded(true); }); return () => { active = false; }; }, [lab.id, session?.user]);
  const step = lab.steps[stepIndex]; const percent = labPercent(stepIndex, lab.steps.length, completed);
  function saveAndAdvance() { const next = advanceLabStep(stepIndex, lab.steps.length); startTransition(async () => { const response = await updateLabProgress({ labId: lab.id, currentStep: next.nextStep, state, completed: next.completed }); if (response.ok) { setStepIndex(response.currentStep); setCompleted(response.completed); setHint(false); setSolution(false); setMessage(response.completed ? "Lab completed." : "Progress saved."); } else setMessage(response.error); }); }
  if (status === "loading" || (session?.user && !loaded)) return <div className="grid min-h-60 place-items-center"><LoaderCircle aria-label="Loading lab" className="size-6 animate-spin text-primary" /></div>;
  if (!session?.user) return <div className="rounded-xl border bg-card p-8 text-center"><LogIn aria-hidden="true" className="mx-auto size-6 text-primary" /><h2 className="mt-4 text-xl font-semibold">Sign in to start this lab.</h2><p className="mt-2 text-sm text-muted-foreground">Your responses and current step will be saved to your learner workspace.</p><Button asChild className="mt-6"><Link href="/signin">Sign in to begin</Link></Button></div>;
  if (completed) return <div className="rounded-xl border border-emerald-500/25 bg-emerald-500/8 p-8 text-center"><div className="mx-auto grid size-11 place-items-center rounded-full bg-emerald-600 text-white"><Check aria-hidden="true" className="size-5" /></div><h2 className="mt-5 text-2xl font-semibold">Engagement complete</h2><p className="mt-2 text-muted-foreground">You worked through every deliverable in {lab.title}.</p><div className="mt-6 flex justify-center gap-3"><Button onClick={() => { setCompleted(false); setStepIndex(0); }}>Review lab</Button><Button asChild variant="outline"><Link href="/labs#field-missions">All field missions</Link></Button></div></div>;
  return <div><div className="flex items-center justify-between text-xs text-muted-foreground"><span>Step {stepIndex + 1} of {lab.steps.length}</span><span>{percent}%</span></div><ProgressBar className="mt-2" label={`${lab.title} progress`} value={percent} /><div className="mt-6 grid gap-6 lg:grid-cols-[220px_1fr]"><ol className="space-y-1">{lab.steps.map((item, index) => <li className={`rounded-md px-3 py-2 text-sm ${index === stepIndex ? "bg-accent font-semibold text-accent-foreground" : index < stepIndex ? "text-foreground" : "text-muted-foreground"}`} key={item.id}><span className="mr-2 font-mono text-[10px]">{index < stepIndex ? "✓" : String(index + 1).padStart(2, "0")}</span>{item.title}</li>)}</ol><section className="rounded-xl border bg-card p-5 sm:p-7"><p className="font-mono text-[10px] font-semibold uppercase tracking-[0.14em] text-primary">{step.type.replaceAll("_", " ")}</p><h2 className="mt-3 text-2xl font-semibold tracking-tight">{step.title}</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">{step.instruction}</p>{step.type !== "content" ? <label className="mt-6 block text-xs font-semibold">Your working notes<textarea className="mt-2 min-h-40 w-full rounded-md border bg-background p-3 text-sm leading-6" onChange={(event) => setState((value) => ({ ...value, [step.id]: event.target.value }))} placeholder="Capture your reasoning and deliverable…" value={state[step.id] ?? ""} /></label> : null}<div className="mt-5 flex flex-wrap gap-2">{step.hint ? <Button onClick={() => setHint((value) => !value)} size="sm" variant="outline"><Lightbulb aria-hidden="true" className="size-4" />{hint ? "Hide hint" : "Show hint"}</Button> : null}{step.solution ? <Button onClick={() => setSolution((value) => !value)} size="sm" variant="ghost"><Eye aria-hidden="true" className="size-4" />{solution ? "Hide solution" : "Reveal solution"}</Button> : null}</div>{hint ? <p className="mt-4 rounded-md bg-accent/45 p-4 text-sm text-muted-foreground"><strong className="text-foreground">Hint:</strong> {step.hint}</p> : null}{solution ? <p className="mt-4 rounded-md border border-primary/20 p-4 text-sm text-muted-foreground"><strong className="text-foreground">Example solution:</strong> {step.solution}</p> : null}<div className="mt-8 flex items-center justify-between border-t pt-5"><Button disabled={stepIndex === 0 || pending} onClick={() => { setStepIndex((value) => value - 1); setHint(false); setSolution(false); }} variant="ghost"><ArrowLeft aria-hidden="true" className="size-4" />Back</Button><div className="text-right"><Button disabled={pending} onClick={saveAndAdvance}>{pending ? <LoaderCircle aria-hidden="true" className="size-4 animate-spin" /> : null}{stepIndex === lab.steps.length - 1 ? "Complete lab" : "Save & continue"}<ArrowRight aria-hidden="true" className="size-4" /></Button><p aria-live="polite" className="mt-1 min-h-4 text-xs text-muted-foreground">{message}</p></div></div></section></div></div>;
}
